load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Include rules_go
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "af47f30e9cbd70ae34e49866e201b3f77069abb111183f2c0297e7e74ba6bbc0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.47.0/rules_go-v0.47.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.47.0/rules_go-v0.47.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.22.6")  # Specify the Go version you need

# Include gazelle
SHA_GAZELLE = "8ad77552825b078a10ad960bec6ef77d2ff8ec70faef2fd038db713f410f5d87"

VERSION_GAZELLE = "0.38.0"

http_archive(
    name = "bazel_gazelle",
    sha256 = SHA_GAZELLE,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v{}/bazel-gazelle-v{}.tar.gz".format(VERSION_GAZELLE, VERSION_GAZELLE),
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_repository(
    name = "com_github_alecthomas_kingpin_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/alecthomas/kingpin/v2",
    sum = "h1:f48lwail6p8zpO1bC4TxtqACaGqHYA22qkHjHpqDjYY=",
    version = "v2.4.0",
)

go_repository(
    name = "com_github_alecthomas_units",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/alecthomas/units",
    sum = "h1:s6gZFSlWYmbqAuRjVTiNNhvNRfY2Wxp9nhfyel4rklc=",
    version = "v0.0.0-20211218093645-b94a6e3cc137",
)

go_repository(
    name = "com_github_antlr4_go_antlr_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/antlr4-go/antlr/v4",
    sum = "h1:lxCg3LAv+EUK6t1i0y1V6/SLeUi0eKEKdhQAlS8TVTI=",
    version = "v4.13.0",
)

go_repository(
    name = "com_github_armon_go_socks5",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/armon/go-socks5",
    sum = "h1:0CwZNZbxp69SHPdPJAN/hZIm0C4OItdklCFmMRWYpio=",
    version = "v0.0.0-20160902184237-e75332964ef5",
)

go_repository(
    name = "com_github_asaskevich_govalidator",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/asaskevich/govalidator",
    sum = "h1:idn718Q4B6AGu/h5Sxe66HYVdqdGu2l9Iebqhi/AEoA=",
    version = "v0.0.0-20190424111038-f61b66f89f4a",
)

go_repository(
    name = "com_github_beorn7_perks",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/beorn7/perks",
    sum = "h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=",
    version = "v1.0.1",
)

go_repository(
    name = "com_github_blang_semver_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/blang/semver/v4",
    sum = "h1:1PFHFE6yCCTv8C1TeyNNarDzntLi7wMI5i/pzqYIsAM=",
    version = "v4.0.0",
)

go_repository(
    name = "com_github_cenkalti_backoff_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/cenkalti/backoff/v4",
    sum = "h1:MyRJ/UdXutAwSAT+s3wNd7MfTIcy71VQueUuFK343L8=",
    version = "v4.3.0",
)

go_repository(
    name = "com_github_cespare_xxhash_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/cespare/xxhash/v2",
    sum = "h1:UL815xU9SqsFlibzuggzjXhog7bL6oX9BbNZnL2UFvs=",
    version = "v2.3.0",
)

go_repository(
    name = "com_github_coreos_go_semver",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/coreos/go-semver",
    sum = "h1:yi21YpKnrx1gt5R+la8n5WgS0kCrsPp33dmEyHReZr4=",
    version = "v0.3.1",
)

go_repository(
    name = "com_github_coreos_go_systemd_v22",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/coreos/go-systemd/v22",
    sum = "h1:RrqgGjYQKalulkV8NGVIfkXQf6YYmOyiJKk8iXXhfZs=",
    version = "v22.5.0",
)

go_repository(
    name = "com_github_creack_pty",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/creack/pty",
    sum = "h1:uDmaGzcdjhF4i/plgjmEsriH11Y0o7RKapEf/LDaM3w=",
    version = "v1.1.9",
)

go_repository(
    name = "com_github_davecgh_go_spew",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/davecgh/go-spew",
    sum = "h1:U9qPSI2PIWSS1VwoXQT9A3Wy9MM3WgvqSxFWenqJduM=",
    version = "v1.1.2-0.20180830191138-d8f796af33cc",
)

go_repository(
    name = "com_github_dustin_go_humanize",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/dustin/go-humanize",
    sum = "h1:GzkhY7T5VNhEkwH0PVJgjz+fX1rhBrR7pRT3mDkpeCY=",
    version = "v1.0.1",
)

go_repository(
    name = "com_github_emicklei_go_restful_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/emicklei/go-restful/v3",
    sum = "h1:rAQeMHw1c7zTmncogyy8VvRZwtkmkZ4FxERmMY4rD+g=",
    version = "v3.11.0",
)

go_repository(
    name = "com_github_evanphx_json_patch",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/evanphx/json-patch",
    sum = "h1:xVCHIVMUu1wtM/VkR9jVZ45N3FhZfYMMYGorLCR8P3k=",
    version = "v0.5.2",
)

go_repository(
    name = "com_github_evanphx_json_patch_v5",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/evanphx/json-patch/v5",
    sum = "h1:kcBlZQbplgElYIlo/n1hJbls2z/1awpXxpRi0/FOJfg=",
    version = "v5.9.0",
)

go_repository(
    name = "com_github_felixge_httpsnoop",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/felixge/httpsnoop",
    sum = "h1:NFTV2Zj1bL4mc9sqWACXbQFVBBg2W3GPvqp8/ESS2Wg=",
    version = "v1.0.4",
)

go_repository(
    name = "com_github_fsnotify_fsnotify",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/fsnotify/fsnotify",
    sum = "h1:8JEhPFa5W2WU7YfeZzPNqzMP6Lwt7L2715Ggo0nosvA=",
    version = "v1.7.0",
)

go_repository(
    name = "com_github_fxamacker_cbor_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/fxamacker/cbor/v2",
    sum = "h1:iM5WgngdRBanHcxugY4JySA0nk1wZorNOpTgCMedv5E=",
    version = "v2.7.0",
)

go_repository(
    name = "com_github_go_kit_log",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-kit/log",
    sum = "h1:MRVx0/zhvdseW+Gza6N9rVzU/IVzaeE1SFI4raAhmBU=",
    version = "v0.2.1",
)

go_repository(
    name = "com_github_go_logfmt_logfmt",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-logfmt/logfmt",
    sum = "h1:otpy5pqBCBZ1ng9RQ0dPu4PN7ba75Y/aA+UpowDyNVA=",
    version = "v0.5.1",
)

go_repository(
    name = "com_github_go_logr_logr",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-logr/logr",
    sum = "h1:6pFjapn8bFcIbiKo3XT4j/BhANplGihG6tvd+8rYgrY=",
    version = "v1.4.2",
)

go_repository(
    name = "com_github_go_logr_stdr",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-logr/stdr",
    sum = "h1:hSWxHoqTgW2S2qGc0LTAI563KZ5YKYRhT3MFKZMbjag=",
    version = "v1.2.2",
)

go_repository(
    name = "com_github_go_logr_zapr",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-logr/zapr",
    sum = "h1:XGdV8XW8zdwFiwOA2Dryh1gj2KRQyOOoNmBy4EplIcQ=",
    version = "v1.3.0",
)

go_repository(
    name = "com_github_go_openapi_jsonpointer",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-openapi/jsonpointer",
    sum = "h1:eCs3fxoIi3Wh6vtgmLTOjdhSpiqphQ+DaPn38N2ZdrE=",
    version = "v0.19.6",
)

go_repository(
    name = "com_github_go_openapi_jsonreference",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-openapi/jsonreference",
    sum = "h1:3sVjiK66+uXK/6oQ8xgcRKcFgQ5KXa2KvnJRumpMGbE=",
    version = "v0.20.2",
)

go_repository(
    name = "com_github_go_openapi_swag",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-openapi/swag",
    sum = "h1:QLMzNJnMGPRNDCbySlcj1x01tzU8/9LTTL9hZZZogBU=",
    version = "v0.22.4",
)

go_repository(
    name = "com_github_go_task_slim_sprig_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/go-task/slim-sprig/v3",
    sum = "h1:sUs3vkvUymDpBKi3qH1YSqBQk9+9D/8M2mN1vB6EwHI=",
    version = "v3.0.0",
)

go_repository(
    name = "com_github_gogo_protobuf",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/gogo/protobuf",
    sum = "h1:Ov1cvc58UF3b5XjBnZv7+opcTcQFZebYjWzi34vdm4Q=",
    version = "v1.3.2",
)

go_repository(
    name = "com_github_golang_groupcache",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/golang/groupcache",
    sum = "h1:oI5xCqsCo564l8iNU+DwB5epxmsaqB+rhGL0m5jtYqE=",
    version = "v0.0.0-20210331224755-41bb18bfe9da",
)

go_repository(
    name = "com_github_golang_jwt_jwt_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/golang-jwt/jwt/v4",
    sum = "h1:7cYmW1XlMY7h7ii7UhUyChSgS5wUJEnm9uZVTGqOWzg=",
    version = "v4.5.0",
)

go_repository(
    name = "com_github_golang_protobuf",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/golang/protobuf",
    sum = "h1:i7eJL8qZTpSEXOPTxNKhASYpMn+8e5Q6AdndVa1dWek=",
    version = "v1.5.4",
)

go_repository(
    name = "com_github_google_btree",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/btree",
    sum = "h1:gK4Kx5IaGY9CD5sPJ36FHiBJ6ZXl0kilRiiCj+jdYp4=",
    version = "v1.0.1",
)

go_repository(
    name = "com_github_google_cel_go",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/cel-go",
    sum = "h1:nDx9r8S3L4pE61eDdt8igGj8rf5kjYR3ILxWIpWNi84=",
    version = "v0.20.1",
)

go_repository(
    name = "com_github_google_gnostic_models",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/gnostic-models",
    sum = "h1:yo/ABAfM5IMRsS1VnXjTBvUb61tFIHozhlYvRgGre9I=",
    version = "v0.6.8",
)

go_repository(
    name = "com_github_google_go_cmp",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/go-cmp",
    sum = "h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=",
    version = "v0.6.0",
)

go_repository(
    name = "com_github_google_gofuzz",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/gofuzz",
    sum = "h1:xRy4A+RhZaiKjJ1bPfwQ8sedCA+YS2YcCHW6ec7JMi0=",
    version = "v1.2.0",
)

go_repository(
    name = "com_github_google_pprof",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/pprof",
    sum = "h1:kmjWCqn2qkEml422C2Rrd27c3VGxi6a/6HNq8QmHRKM=",
    version = "v0.0.0-20240525223248-4bfdf5a9a2af",
)

go_repository(
    name = "com_github_google_uuid",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/google/uuid",
    sum = "h1:NIvaJDMOsjHA8n1jAhLSgzrAzy1Hgr+hNrb57e+94F0=",
    version = "v1.6.0",
)

go_repository(
    name = "com_github_gorilla_websocket",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/gorilla/websocket",
    sum = "h1:PPwGk2jz7EePpoHN/+ClbZu8SPxiqlu12wZP/3sWmnc=",
    version = "v1.5.0",
)

go_repository(
    name = "com_github_gregjones_httpcache",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/gregjones/httpcache",
    sum = "h1:pdN6V1QBWetyv/0+wjACpqVH+eVULgEjkurDLq3goeM=",
    version = "v0.0.0-20180305231024-9cad4c3443a7",
)

go_repository(
    name = "com_github_grpc_ecosystem_go_grpc_middleware",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/grpc-ecosystem/go-grpc-middleware",
    sum = "h1:+9834+KizmvFV7pXQGSXQTsaWhq2GjuNUt0aUU0YBYw=",
    version = "v1.3.0",
)

go_repository(
    name = "com_github_grpc_ecosystem_go_grpc_prometheus",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/grpc-ecosystem/go-grpc-prometheus",
    sum = "h1:Ovs26xHkKqVztRpIrF/92BcuyuQ/YW4NSIpoGtfXNho=",
    version = "v1.2.0",
)

go_repository(
    name = "com_github_grpc_ecosystem_grpc_gateway",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/grpc-ecosystem/grpc-gateway",
    sum = "h1:gmcG1KaJ57LophUzW0Hy8NmPhnMZb4M0+kPpLofRdBo=",
    version = "v1.16.0",
)

go_repository(
    name = "com_github_grpc_ecosystem_grpc_gateway_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/grpc-ecosystem/grpc-gateway/v2",
    sum = "h1:bkypFPDjIYGfCYD5mRBvpqxfYX1YCS1PXdKYWi8FsN0=",
    version = "v2.20.0",
)

go_repository(
    name = "com_github_imdario_mergo",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/imdario/mergo",
    sum = "h1:xTNEAn+kxVO7dTZGu0CegyqKZmoWFI0rF8UxjlB2d28=",
    version = "v0.3.6",
)

go_repository(
    name = "com_github_inconshreveable_mousetrap",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/inconshreveable/mousetrap",
    sum = "h1:wN+x4NVGpMsO7ErUn/mUI3vEoE6Jt13X2s0bqwp9tc8=",
    version = "v1.1.0",
)

go_repository(
    name = "com_github_jessevdk_go_flags",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/jessevdk/go-flags",
    sum = "h1:4IU2WS7AumrZ/40jfhf4QVDMsQwqA7VEHozFRrGARJA=",
    version = "v1.4.0",
)

go_repository(
    name = "com_github_jonboulle_clockwork",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/jonboulle/clockwork",
    sum = "h1:UOGuzwb1PwsrDAObMuhUnj0p5ULPj8V/xJ7Kx9qUBdQ=",
    version = "v0.2.2",
)

go_repository(
    name = "com_github_josharian_intern",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/josharian/intern",
    sum = "h1:vlS4z54oSdjm0bgjRigI+G1HpF+tI+9rE5LLzOg8HmY=",
    version = "v1.0.0",
)

go_repository(
    name = "com_github_jpillora_backoff",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/jpillora/backoff",
    sum = "h1:uvFg412JmmHBHw7iwprIxkPMI+sGQ4kzOWsMeHnm2EA=",
    version = "v1.0.0",
)

go_repository(
    name = "com_github_json_iterator_go",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/json-iterator/go",
    sum = "h1:PV8peI4a0ysnczrg+LtxykD8LfKY9ML6u2jnxaEnrnM=",
    version = "v1.1.12",
)

go_repository(
    name = "com_github_julienschmidt_httprouter",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/julienschmidt/httprouter",
    sum = "h1:U0609e9tgbseu3rBINet9P48AI/D3oJs4dN7jwJOQ1U=",
    version = "v1.3.0",
)

go_repository(
    name = "com_github_kisielk_errcheck",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/kisielk/errcheck",
    sum = "h1:e8esj/e4R+SAOwFwN+n3zr0nYeCyeweozKfO23MvHzY=",
    version = "v1.5.0",
)

go_repository(
    name = "com_github_kisielk_gotool",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/kisielk/gotool",
    sum = "h1:AV2c/EiW3KqPNT9ZKl07ehoAGi4C5/01Cfbblndcapg=",
    version = "v1.0.0",
)

go_repository(
    name = "com_github_kr_pretty",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/kr/pretty",
    sum = "h1:flRD4NNwYAUpkphVc1HcthR4KEIFJ65n8Mw5qdRn3LE=",
    version = "v0.3.1",
)

go_repository(
    name = "com_github_kr_pty",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/kr/pty",
    sum = "h1:VkoXIwSboBpnk99O/KFauAEILuNHv5DVFKZMBN/gUgw=",
    version = "v1.1.1",
)

go_repository(
    name = "com_github_kr_text",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/kr/text",
    sum = "h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=",
    version = "v0.2.0",
)

go_repository(
    name = "com_github_mailru_easyjson",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/mailru/easyjson",
    sum = "h1:UGYAvKxe3sBsEDzO8ZeWOSlIQfWFlxbzLZe7hwFURr0=",
    version = "v0.7.7",
)

go_repository(
    name = "com_github_moby_spdystream",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/moby/spdystream",
    sum = "h1:Vy79D6mHeJJjiPdFEL2yku1kl0chZpJfZcPpb16BRl8=",
    version = "v0.4.0",
)

go_repository(
    name = "com_github_modern_go_concurrent",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/modern-go/concurrent",
    sum = "h1:TRLaZ9cD/w8PVh93nsPXa1VrQ6jlwL5oN8l14QlcNfg=",
    version = "v0.0.0-20180306012644-bacd9c7ef1dd",
)

go_repository(
    name = "com_github_modern_go_reflect2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/modern-go/reflect2",
    sum = "h1:xBagoLtFs94CBntxluKeaWgTMpvLxC4ur3nMaC9Gz0M=",
    version = "v1.0.2",
)

go_repository(
    name = "com_github_munnerz_goautoneg",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/munnerz/goautoneg",
    sum = "h1:C3w9PqII01/Oq1c1nUAm88MOHcQC9l5mIlSMApZMrHA=",
    version = "v0.0.0-20191010083416-a7dc8b61c822",
)

go_repository(
    name = "com_github_mwitkow_go_conntrack",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/mwitkow/go-conntrack",
    sum = "h1:KUppIJq7/+SVif2QVs3tOP0zanoHgBEVAwHxUSIzRqU=",
    version = "v0.0.0-20190716064945-2f068394615f",
)

go_repository(
    name = "com_github_mxk_go_flowrate",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/mxk/go-flowrate",
    sum = "h1:y5//uYreIhSUg3J1GEMiLbxo1LJaP8RfCpH6pymGZus=",
    version = "v0.0.0-20140419014527-cca7078d478f",
)

go_repository(
    name = "com_github_nytimes_gziphandler",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/NYTimes/gziphandler",
    sum = "h1:ZUDjpQae29j0ryrS0u/B8HZfJBtBQHjqw2rQ2cqUQ3I=",
    version = "v1.1.1",
)

go_repository(
    name = "com_github_onsi_ginkgo_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/onsi/ginkgo/v2",
    sum = "h1:9Cnnf7UHo57Hy3k6/m5k3dRfGTMXGvxhHFvkDTCTpvA=",
    version = "v2.19.0",
)

go_repository(
    name = "com_github_onsi_gomega",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/onsi/gomega",
    sum = "h1:dsYjIxxSR755MDmKVsaFQTE22ChNBcuuTWgkUDSubOk=",
    version = "v1.33.1",
)

go_repository(
    name = "com_github_peterbourgon_diskv",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/peterbourgon/diskv",
    sum = "h1:UBdAOUP5p4RWqPBg048CAvpKN+vxiaj6gdUUzhl4XmI=",
    version = "v2.0.1+incompatible",
)

go_repository(
    name = "com_github_pkg_errors",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/pkg/errors",
    sum = "h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=",
    version = "v0.9.1",
)

go_repository(
    name = "com_github_pmezard_go_difflib",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/pmezard/go-difflib",
    sum = "h1:Jamvg5psRIccs7FGNTlIRMkT8wgtp5eCXdBlqhYGL6U=",
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2",
)

go_repository(
    name = "com_github_prometheus_client_golang",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/prometheus/client_golang",
    sum = "h1:wZWJDwK+NameRJuPGDhlnFgx8e8HN3XHQeLaYJFJBOE=",
    version = "v1.19.1",
)

go_repository(
    name = "com_github_prometheus_client_model",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/prometheus/client_model",
    sum = "h1:ZKSh/rekM+n3CeS952MLRAdFwIKqeY8b62p8ais2e9E=",
    version = "v0.6.1",
)

go_repository(
    name = "com_github_prometheus_common",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/prometheus/common",
    sum = "h1:KEi6DK7lXW/m7Ig5i47x0vRzuBsHuvJdi5ee6Y3G1dc=",
    version = "v0.55.0",
)

go_repository(
    name = "com_github_prometheus_procfs",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/prometheus/procfs",
    sum = "h1:YagwOFzUgYfKKHX6Dr+sHT7km/hxC76UB0learggepc=",
    version = "v0.15.1",
)

go_repository(
    name = "com_github_rogpeppe_go_internal",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/rogpeppe/go-internal",
    sum = "h1:exVL4IDcn6na9z1rAb56Vxr+CgyK3nn3O+epU5NdKM8=",
    version = "v1.12.0",
)

go_repository(
    name = "com_github_sirupsen_logrus",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/sirupsen/logrus",
    sum = "h1:dueUQJ1C2q9oE3F7wvmSGAaVtTmUizReu6fjN8uqzbQ=",
    version = "v1.9.3",
)

go_repository(
    name = "com_github_soheilhy_cmux",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/soheilhy/cmux",
    sum = "h1:jjzc5WVemNEDTLwv9tlmemhC73tI08BNOIGwBOo10Js=",
    version = "v0.1.5",
)

go_repository(
    name = "com_github_spf13_cobra",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/spf13/cobra",
    sum = "h1:e5/vxKd/rZsfSJMUX1agtjeTDf+qv1/JdBF8gg5k9ZM=",
    version = "v1.8.1",
)

go_repository(
    name = "com_github_spf13_pflag",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/spf13/pflag",
    sum = "h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=",
    version = "v1.0.5",
)

go_repository(
    name = "com_github_stoewer_go_strcase",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/stoewer/go-strcase",
    sum = "h1:Z2iHWqGXH00XYgqDmNgQbIBxf3wrNq0F3feEy0ainaU=",
    version = "v1.2.0",
)

go_repository(
    name = "com_github_stretchr_objx",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/stretchr/objx",
    sum = "h1:1zr/of2m5FGMsad5YfcqgdqdWrIhu+EBEJRhR1U7z/c=",
    version = "v0.5.0",
)

go_repository(
    name = "com_github_stretchr_testify",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/stretchr/testify",
    sum = "h1:HtqpIVDClZ4nwg75+f6Lvsy/wHu+3BoSGCbBAcpTsTg=",
    version = "v1.9.0",
)

go_repository(
    name = "com_github_tmc_grpc_websocket_proxy",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/tmc/grpc-websocket-proxy",
    sum = "h1:6fotK7otjonDflCTK0BCfls4SPy3NcCVb5dqqmbRknE=",
    version = "v0.0.0-20220101234140-673ab2c3ae75",
)

go_repository(
    name = "com_github_x448_float16",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/x448/float16",
    sum = "h1:qLwI1I70+NjRFUR3zs1JPUCgaCXSh3SW62uAKT1mSBM=",
    version = "v0.8.4",
)

go_repository(
    name = "com_github_xhit_go_str2duration_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/xhit/go-str2duration/v2",
    sum = "h1:lxklc02Drh6ynqX+DdPyp5pCKLUQpRT8bp8Ydu2Bstc=",
    version = "v2.1.0",
)

go_repository(
    name = "com_github_xiang90_probing",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/xiang90/probing",
    sum = "h1:eY9dn8+vbi4tKz5Qo6v2eYzo7kUS51QINcR5jNpbZS8=",
    version = "v0.0.0-20190116061207-43a291ad63a2",
)

go_repository(
    name = "com_github_yuin_goldmark",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/yuin/goldmark",
    sum = "h1:ruQGxdhGHe7FWOJPT0mKs5+pD2Xs1Bm/kdGlHO04FmM=",
    version = "v1.2.1",
)

go_repository(
    name = "com_google_cloud_go_compute_metadata",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "cloud.google.com/go/compute/metadata",
    sum = "h1:Tz+eQXMEqDIKRsmY3cHTL6FVaynIjX2QxYC4trgAKZc=",
    version = "v0.3.0",
)

go_repository(
    name = "in_gopkg_check_v1",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/check.v1",
    sum = "h1:Hei/4ADfdWqJk1ZMxUNpqntNwaWcugrBjAiHlqqRiVk=",
    version = "v1.0.0-20201130134442-10cb98267c6c",
)

go_repository(
    name = "in_gopkg_evanphx_json_patch_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/evanphx/json-patch.v4",
    sum = "h1:n6jtcsulIzXPJaxegRbvFNNrZDjbij7ny3gmSPG+6V4=",
    version = "v4.12.0",
)

go_repository(
    name = "in_gopkg_inf_v0",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/inf.v0",
    sum = "h1:73M5CoZyi3ZLMOyDlQh031Cx6N9NDJ2Vvfl76EDAgDc=",
    version = "v0.9.1",
)

go_repository(
    name = "in_gopkg_natefinch_lumberjack_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/natefinch/lumberjack.v2",
    sum = "h1:bBRl1b0OH9s/DuPhuXpNl+VtCaJXFZ5/uEFST95x9zc=",
    version = "v2.2.1",
)

go_repository(
    name = "in_gopkg_yaml_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/yaml.v2",
    sum = "h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=",
    version = "v2.4.0",
)

go_repository(
    name = "in_gopkg_yaml_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/yaml.v3",
    sum = "h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=",
    version = "v3.0.1",
)

go_repository(
    name = "io_etcd_go_bbolt",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/bbolt",
    sum = "h1:8x7aARPEXiXbHmtUwAIv7eV2fQFHrLLavdiJ3uzJXoI=",
    version = "v1.3.9",
)

go_repository(
    name = "io_etcd_go_etcd_api_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/api/v3",
    sum = "h1:vHObSCxyB9zlF60w7qzAdTcGaglbJOpSj1Xj9+WGxq0=",
    version = "v3.5.14",
)

go_repository(
    name = "io_etcd_go_etcd_client_pkg_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/client/pkg/v3",
    sum = "h1:SaNH6Y+rVEdxfpA2Jr5wkEvN6Zykme5+YnbCkxvuWxQ=",
    version = "v3.5.14",
)

go_repository(
    name = "io_etcd_go_etcd_client_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/client/v2",
    sum = "h1:RWfV1SX5jTU0lbCvpVQe3iPQeAHETWdOTb6pxhd77C8=",
    version = "v2.305.13",
)

go_repository(
    name = "io_etcd_go_etcd_client_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/client/v3",
    sum = "h1:CWfRs4FDaDoSz81giL7zPpZH2Z35tbOrAJkkjMqOupg=",
    version = "v3.5.14",
)

go_repository(
    name = "io_etcd_go_etcd_pkg_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/pkg/v3",
    sum = "h1:st9bDWNsKkBNpP4PR1MvM/9NqUPfvYZx/YXegsYEH8M=",
    version = "v3.5.13",
)

go_repository(
    name = "io_etcd_go_etcd_raft_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/raft/v3",
    sum = "h1:7r/NKAOups1YnKcfro2RvGGo2PTuizF/xh26Z2CTAzA=",
    version = "v3.5.13",
)

go_repository(
    name = "io_etcd_go_etcd_server_v3",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.etcd.io/etcd/server/v3",
    sum = "h1:V6KG+yMfMSqWt+lGnhFpP5z5dRUj1BDRJ5k1fQ9DFok=",
    version = "v3.5.13",
)

go_repository(
    name = "io_k8s_api",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/api",
    sum = "h1:b9LiSjR2ym/SzTOlfMHm1tr7/21aD7fSkqgD/CVJBCo=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_apiextensions_apiserver",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/apiextensions-apiserver",
    sum = "h1:fZgCVhGwsclj3qCw1buVXCV6khjRzKC5eCFt24kyLSk=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_apimachinery",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/apimachinery",
    sum = "h1:mhcUBbj7KUjaVhyXILglcVjuS4nYXiwC+KKFBgIVy7U=",
    version = "v0.31.1",
)

go_repository(
    name = "io_k8s_apiserver",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/apiserver",
    sum = "h1:p+2dgJjy+bk+B1Csz+mc2wl5gHwvNkC9QJV+w55LVrY=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_client_go",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/client-go",
    sum = "h1:QqEJzNjbN2Yv1H79SsS+SWnXkBgVu4Pj3CJQgbx0gI8=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_code_generator",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/code-generator",
    sum = "h1:w607nrMi1KeDKB3/F/J4lIoOgAwc+gV9ZKew4XRfMp8=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_component_base",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/component-base",
    sum = "h1:/KIzGM5EvPNQcYgwq5NwoQBaOlVFrghoVGr8lG6vNRs=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_gengo_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/gengo/v2",
    sum = "h1:NGrVE502P0s0/1hudf8zjgwki1X/TByhmAoILTarmzo=",
    version = "v2.0.0-20240228010128-51d4e06bde70",
)

go_repository(
    name = "io_k8s_klog_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/klog/v2",
    sum = "h1:n9Xl7H1Xvksem4KFG4PYbdQCQxqc/tTUyrgXaOhHSzk=",
    version = "v2.130.1",
)

go_repository(
    name = "io_k8s_kms",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/kms",
    sum = "h1:KchILPfB1ZE+ka7223mpU5zeFNkmb45jl7RHnlImUaI=",
    version = "v0.31.0",
)

go_repository(
    name = "io_k8s_kube_openapi",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/kube-openapi",
    sum = "h1:BZqlfIlq5YbRMFko6/PM7FjZpUb45WallggurYhKGag=",
    version = "v0.0.0-20240228011516-70dd3763d340",
)

go_repository(
    name = "io_k8s_sigs_apiserver_network_proxy_konnectivity_client",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/apiserver-network-proxy/konnectivity-client",
    sum = "h1:2770sDpzrjjsAtVhSeUFseziht227YAWYHLGNM8QPwY=",
    version = "v0.30.3",
)

go_repository(
    name = "io_k8s_sigs_controller_runtime",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/controller-runtime",
    sum = "h1:nWVM7aq+Il2ABxwiCizrVDSlmDcshi9llbaFbC0ji/Q=",
    version = "v0.19.0",
)

go_repository(
    name = "io_k8s_sigs_json",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/json",
    sum = "h1:EDPBXCAspyGV4jQlpZSudPeMmr1bNJefnuqLsRAsHZo=",
    version = "v0.0.0-20221116044647-bc3834ca7abd",
)

go_repository(
    name = "io_k8s_sigs_structured_merge_diff_v4",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/structured-merge-diff/v4",
    sum = "h1:150L+0vs/8DA78h1u02ooW1/fFq/Lwr+sGiqlzvrtq4=",
    version = "v4.4.1",
)

go_repository(
    name = "io_k8s_sigs_yaml",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/yaml",
    sum = "h1:Mk1wCc2gy/F0THH0TAp1QYyJNzRm2KCLy3o5ASXVI5E=",
    version = "v1.4.0",
)

go_repository(
    name = "io_k8s_utils",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "k8s.io/utils",
    sum = "h1:pUdcCO1Lk/tbT5ztQWOBi5HBgbBP1J8+AsQnQCKsi8A=",
    version = "v0.0.0-20240711033017-18e509b52bc8",
)

go_repository(
    name = "io_opentelemetry_go_contrib_instrumentation_google_golang_org_grpc_otelgrpc",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    #    build_file_generation = "on",
    #    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc",
    sum = "h1:9G6E0TXzGFVfTnawRzrPl83iHOAV7L8NJiR8RSGYV1g=",
    version = "v0.53.0",
)

go_repository(
    name = "io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp",
    sum = "h1:4K4tsIXefpVJtvA/8srF4V4y0akAoPHkIslgAkjixJA=",
    version = "v0.53.0",
)

go_repository(
    name = "io_opentelemetry_go_otel",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel",
    sum = "h1:/SqNcYk+idO0CxKEUOtKQClMK/MimZihKYMruSMViUo=",
    version = "v1.28.0",
)

go_repository(
    name = "io_opentelemetry_go_otel_exporters_otlp_otlptrace",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel/exporters/otlp/otlptrace",
    sum = "h1:3Q/xZUyC1BBkualc9ROb4G8qkH90LXEIICcs5zv1OYY=",
    version = "v1.28.0",
)

go_repository(
    name = "io_opentelemetry_go_otel_exporters_otlp_otlptrace_otlptracegrpc",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc",
    sum = "h1:qFffATk0X+HD+f1Z8lswGiOQYKHRlzfmdJm0wEaVrFA=",
    version = "v1.27.0",
)

go_repository(
    name = "io_opentelemetry_go_otel_metric",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel/metric",
    sum = "h1:f0HGvSl1KRAU1DLgLGFjrwVyismPlnuU6JD6bOeuA5Q=",
    version = "v1.28.0",
)

go_repository(
    name = "io_opentelemetry_go_otel_sdk",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel/sdk",
    sum = "h1:b9d7hIry8yZsgtbmM0DKyPWMMUMlK9NEKuIG4aBqWyE=",
    version = "v1.28.0",
)

go_repository(
    name = "io_opentelemetry_go_otel_trace",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/otel/trace",
    sum = "h1:GhQ9cUuQGmNDd5BTCP2dAvv75RdMxEfTmYejp+lkx9g=",
    version = "v1.28.0",
)

go_repository(
    name = "io_opentelemetry_go_proto_otlp",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.opentelemetry.io/proto/otlp",
    sum = "h1:TrMUixzpM0yuc/znrFTP9MMRh8trP93mkCiDVeXrui0=",
    version = "v1.3.1",
)

go_repository(
    name = "org_golang_google_appengine",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/appengine",
    sum = "h1:FZR1q0exgwxzPzp/aF+VccGrSfxfPpkBqjIIEq3ru6c=",
    version = "v1.6.7",
)

go_repository(
    name = "org_golang_google_genproto",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/genproto",
    sum = "h1:VBu5YqKPv6XiJ199exd8Br+Aetz+o08F+PLMnwJQHAY=",
    version = "v0.0.0-20230822172742-b8732ec3820d",
)

go_repository(
    name = "org_golang_google_genproto_googleapis_api",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/genproto/googleapis/api",
    sum = "h1:7whR9kGa5LUwFtpLm2ArCEejtnxlGeLbAyjFY8sGNFw=",
    version = "v0.0.0-20240528184218-531527333157",
)

go_repository(
    name = "org_golang_google_genproto_googleapis_rpc",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/genproto/googleapis/rpc",
    sum = "h1:BwIjyKYGsK9dMCBOorzRri8MQwmi7mT9rGHsCEinZkA=",
    version = "v0.0.0-20240701130421-f6361c86f094",
)

go_repository(
    name = "org_golang_google_grpc",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/grpc",
    sum = "h1:bs/cUb4lp1G5iImFFd3u5ixQzweKizoZJAwBNLR42lc=",
    version = "v1.65.0",
)

go_repository(
    name = "org_golang_google_protobuf",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    #    build_file_generation = "on",
    #    build_file_proto_mode = "disable",
    importpath = "google.golang.org/protobuf",
    sum = "h1:6xV6lTsCfpGD21XK49h7MhtcApnLqkfYgPcdHftf6hg=",
    version = "v1.34.2",
)

go_repository(
    name = "org_golang_x_crypto",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/crypto",
    sum = "h1:RrRspgV4mU+YwB4FYnuBoKsUapNIL5cohGAmSH3azsw=",
    version = "v0.26.0",
)

go_repository(
    name = "org_golang_x_exp",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/exp",
    sum = "h1:mCRnTeVUjcrhlRmO0VK8a6k6Rrf6TF9htwo2pJVSjIU=",
    version = "v0.0.0-20230515195305-f3d0a9c9a5cc",
)

go_repository(
    name = "org_golang_x_mod",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/mod",
    sum = "h1:zY54UmvipHiNd+pm+m0x9KhZ9hl1/7QNMyxXbc6ICqA=",
    version = "v0.17.0",
)

go_repository(
    name = "org_golang_x_net",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/net",
    sum = "h1:a9JDOJc5GMUJ0+UDqmLT86WiEy7iWyIhz8gz8E4e5hE=",
    version = "v0.28.0",
)

go_repository(
    name = "org_golang_x_oauth2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/oauth2",
    sum = "h1:tsimM75w1tF/uws5rbeHzIWxEqElMehnc+iW793zsZs=",
    version = "v0.21.0",
)

go_repository(
    name = "org_golang_x_sync",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/sync",
    sum = "h1:3NFvSEYkUoMifnESzZl15y791HH1qU2xm6eCJU5ZPXQ=",
    version = "v0.8.0",
)

go_repository(
    name = "org_golang_x_sys",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/sys",
    sum = "h1:Twjiwq9dn6R1fQcyiK+wQyHWfaz/BJB+YIpzU/Cv3Xg=",
    version = "v0.24.0",
)

go_repository(
    name = "org_golang_x_term",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/term",
    sum = "h1:F6D4vR+EHoL9/sWAWgAR1H2DcHr4PareCbAaCo1RpuU=",
    version = "v0.23.0",
)

go_repository(
    name = "org_golang_x_text",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/text",
    sum = "h1:XtiM5bkSOt+ewxlOE/aE/AKEHibwj/6gvWMl9Rsh0Qc=",
    version = "v0.17.0",
)

go_repository(
    name = "org_golang_x_time",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/time",
    sum = "h1:rg5rLMjNzMS1RkNLzCG38eapWhnYLFYXDXj2gOlr8j4=",
    version = "v0.3.0",
)

go_repository(
    name = "org_golang_x_tools",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/tools",
    sum = "h1:vU5i/LfpvrRCpgM/VPfJLg5KjxD3E+hfT1SH+d9zLwg=",
    version = "v0.21.1-0.20240508182429-e35e4ccd0d2d",
)

go_repository(
    name = "org_golang_x_xerrors",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "golang.org/x/xerrors",
    sum = "h1:H2TDz8ibqkAF6YGhCdN3jS9O0/s90v0rJh3X/OLHEUk=",
    version = "v0.0.0-20220907171357-04be3eba64a2",
)

go_repository(
    name = "org_uber_go_goleak",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.uber.org/goleak",
    sum = "h1:2K3zAYmnTNqV73imy9J1T3WC+gmCePx2hEGkimedGto=",
    version = "v1.3.0",
)

go_repository(
    name = "org_uber_go_multierr",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.uber.org/multierr",
    sum = "h1:blXXJkSxSSfBVBlC76pxqeO+LN3aDfLQo+309xJstO0=",
    version = "v1.11.0",
)

go_repository(
    name = "org_uber_go_zap",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "go.uber.org/zap",
    sum = "h1:sI7k6L95XOKS281NhVKOFCUNIvv9e0w4BF8N3u+tCRo=",
    version = "v1.26.0",
)

go_repository(
    name = "xyz_gomodules_jsonpatch_v2",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gomodules.xyz/jsonpatch/v2",
    sum = "h1:Ci3iUJyx9UeRx7CeFN8ARgGbkESwJK+KB9lLcWxY/Zw=",
    version = "v2.4.0",
)

go_repository(
    name = "com_github_fatih_color",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/fatih/color",
    sum = "h1:kOqh6YHBtK8aywxGerMG2Eq3H6Qgoqeo13Bk2Mv/nBs=",
    version = "v1.15.0",
)

go_repository(
    name = "com_github_gobuffalo_flect",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/gobuffalo/flect",
    sum = "h1:eqjPGSo2WmjgY2XlpGwo2NXgL3RucAKo4k4qQMNA5sA=",
    version = "v1.0.2",
)

go_repository(
    name = "com_github_mattn_go_colorable",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/mattn/go-colorable",
    sum = "h1:fFA4WZxdEF4tXPZVKMLwD8oUnCTTo08duU7wxecdEvA=",
    version = "v0.1.13",
)

go_repository(
    name = "com_github_mattn_go_isatty",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/mattn/go-isatty",
    sum = "h1:BTarxUcIeDqL27Mc+vyvdWYSL28zpIhv3RoTdsLMPng=",
    version = "v0.0.17",
)

go_repository(
    name = "com_github_nxadm_tail",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/nxadm/tail",
    sum = "h1:nPr65rt6Y5JFSKQO7qToXr7pePgD6Gwiw05lkbyAQTE=",
    version = "v1.4.8",
)

go_repository(
    name = "com_github_onsi_ginkgo",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "github.com/onsi/ginkgo",
    sum = "h1:8xi0RTUf59SOSfEtZMvwTvXYMzG4gV23XVHOZiXNtnE=",
    version = "v1.16.5",
)

go_repository(
    name = "in_gopkg_tomb_v1",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "gopkg.in/tomb.v1",
    sum = "h1:uRGJdciOHaEIrze2W8Q3AKkepLTh2hOroT7a+7czfdQ=",
    version = "v1.0.0-20141024135613-dd632973f1e7",
)

go_repository(
    name = "io_k8s_sigs_controller_tools",
    build_file_generation = "on",
    build_file_proto_mode = "disable",
    importpath = "sigs.k8s.io/controller-tools",
    sum = "h1:TY6CGE6+6hzO7hhJFte65ud3cFmmZW947jajXkuDfBw=",
    version = "v0.12.0",
)

gazelle_dependencies()

# Include rules_pkg
http_archive(
    name = "rules_pkg",
    sha256 = "335632735e625d408870ec3e361e192e99ef7462315caa887417f4d88c4c8fb8",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.9.0/rules_pkg-0.9.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.9.0/rules_pkg-0.9.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

# Include rules_kubebuilder repository
local_repository(
    name = "rules_kubebuilder",
    path = "/home/ckaidos/git/rules_kubebuilder",
)

load("@rules_kubebuilder//controller-gen:deps.bzl", "controller_gen_register_toolchains")

controller_gen_register_toolchains(controller_gen_binary = "@io_k8s_sigs_controller_tools//cmd/controller-gen")
